python3 ASTARBusQ.py ./ASTAR-tests/students01.prob 1
python3 ASTARBusQ.py ./ASTAR-tests/students01.prob 2
python3 ASTARBusQ.py ./ASTAR-tests/students02.prob 1
python3 ASTARBusQ.py ./ASTAR-tests/students02.prob 2
python3 ASTARBusQ.py ./ASTAR-tests/students03.prob 1
python3 ASTARBusQ.py ./ASTAR-tests/students03.prob 2
python3 ASTARBusQ.py ./ASTAR-tests/students04.prob 1
python3 ASTARBusQ.py ./ASTAR-tests/students04.prob 2
python3 ASTARBusQ.py ./ASTAR-tests/students05.prob 1
python3 ASTARBusQ.py ./ASTAR-tests/students05.prob 2
python3 ASTARBusQ.py ./ASTAR-tests/students06.prob 1
python3 ASTARBusQ.py ./ASTAR-tests/students06.prob 2
python3 ASTARBusQ.py ./ASTAR-tests/students07.prob 1
python3 ASTARBusQ.py ./ASTAR-tests/students07.prob 2